# Generated by Django 2.2.5 on 2019-09-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('valor_unitario', models.FloatField(max_length=50, verbose_name='Valor unitário')),
                ('qtd_estoque', models.IntegerField(verbose_name='Quantidade no estoque')),
                ('situacao_prod', models.CharField(choices=[('0', 'Indisponivel'), ('1', 'Disponivel')], max_length=50, verbose_name='Status do produto')),
            ],
        ),
    ]
