# Generated by Django 2.2.5 on 2019-09-04 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_produtos', models.IntegerField(verbose_name='Quantidade de produtos pedidos')),
                ('valor_unitario', models.FloatField(max_length=50, verbose_name='Valor por unidade do produto')),
                ('data_pedido', models.DateField()),
                ('solicitante', models.CharField(max_length=100, verbose_name='Nome do solicitante')),
                ('endereco_solicitante', models.CharField(max_length=100, verbose_name='Endereço do solicitante')),
                ('despachante', models.CharField(max_length=100, verbose_name='Nome do despachante')),
                ('situacao_pedido', models.CharField(choices=[('0', 'Pendente'), ('1', 'Enviado'), ('2', 'Entregue')], max_length=10, verbose_name='Status do pedido')),
                ('nome_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produtos', verbose_name='Produto')),
            ],
        ),
    ]
